version: '3'

x-env-generic-backend: &x-env-generic-backend
  TZ: Europe/Stockholm
  WHARF_API_URL: http://api:8080
  WHARF_HTTP_CORS_ALLOWALLORIGINS: "true"

services:
  proxy:
    image: amd64/traefik:v2.5
    tty: true
    ports:
    - "5000:8081"
    volumes:
    - ./wharf-docker-compose/traefik:/etc/traefik # Traefik configuration file
  web:
    image: quay.io/iver-wharf/wharf-web
  api:
    image: quay.io/iver-wharf/wharf-api
    tty: true
    ports:
    - "5001:8080"
    environment:
      <<: *x-env-generic-backend
      WHARF_DB_DRIVER: postgres
      WHARF_DB_HOST: db
      WHARF_DB_PORT: 5432
      WHARF_DB_USERNAME: postgres
      WHARF_DB_PASSWORD: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
      WHARF_DB_NAME: wharf
      WHARF_DB_LOG: "true"
      MOCK_LOCAL_CI_RESPONSE: "true"
      WHARF_INSTANCE: local
  provider-gitlab:
    image: quay.io/iver-wharf/wharf-provider-gitlab
    tty: true
    ports:
    - "5002:8080"
    environment:
      <<: *x-env-generic-backend
  provider-github:
    image: quay.io/iver-wharf/wharf-provider-github
    tty: true
    ports:
    - "5003:8080"
    environment:
      <<: *x-env-generic-backend
  provider-azuredevops:
    image: quay.io/iver-wharf/wharf-provider-azuredevops
    tty: true
    ports:
    - "5004:8080"
    environment:
      <<: *x-env-generic-backend
  db:
    image: postgres
    restart: always
    environment:
      <<: *x-env-generic-backend
      POSTGRES_PASSWORD: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
    ports:
      - "5432:5432"
    volumes:
      - wharf-postgresql-volume:/var/lib/postgresql/data
volumes:
  wharf-postgresql-volume:
