#version: '3'
services:
  proxy:
    image: traefik:1.7.10-alpine
    ports:
    - "5000:8081"
    volumes:
    - ./wharf-docker-compose/traefik:/etc/traefik # Traefik configuration file
  web:
    image: quay.io/iver-wharf/wharf-web
  api:
    image: quay.io/iver-wharf/wharf-api
    ports:
    - "5001:8080"
    environment:
    - WHARF_DB_DRIVER=postgres
    - WHARF_DB_NAME=wharf
    - WHARF_DB_HOST=DB
    - WHARF_DB_USERNAME=postgres
    - WHARF_DB_PASSWORD=OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
    - WHARF_DB_PORT=5432
    - WHARF_DB_LOG=true
    - WHARF_HTTP_OIDC_ENABLE=0
    - MOCK_LOCAL_CI_RESPONSE=true
    - WHARF_INSTANCE=local
    depends_on:
      db:
        condition: service_healthy
  provider-gitlab:
    image: quay.io/iver-wharf/wharf-provider-gitlab
    ports:
    - "5002:8080"
    environment:
    - WHARF_API_URL=http://api:8080
    - ALLOW_CORS=YES
  provider-github:
    image: quay.io/iver-wharf/wharf-provider-github
    ports:
    - "5003:8080"
    environment:
    - WHARF_API_URL=http://api:8080
    - ALLOW_CORS=YES
  provider-azuredevops:
    image: quay.io/iver-wharf/wharf-provider-azuredevops
    ports:
    - "5004:8080"
    environment:
    - WHARF_API_URL=http://api:8080
    - ALLOW_CORS=YES
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
    ports:
    - 5432:5432
    volumes:
    - ./api-postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
