version: '3'
services:
  ## This disables wharf-web, which lets you run wharf-web locally
  ## via `npm start` instead. Comment this out to reenable it
  web:
    deploy:
      replicas: 0
  ## Or uncomment this to also build the wharf-web service from source.
  ## Slight warning that it does take significantly more time to build than
  ## the other services though.
  #web:
  #  build: wharf-web
  api:
    build:
      context: wharf-api
      args:
        BUILD_VERSION: local docker-compose
  provider-gitlab:
    build:
      context: wharf-provider-gitlab
      args:
        BUILD_VERSION: local docker-compose
  provider-github:
    build:
      context: wharf-provider-github
      args:
        BUILD_VERSION: local docker-compose
  provider-azuredevops:
    build:
      context: wharf-provider-azuredevops
      args:
        BUILD_VERSION: local docker-compose
