version: '3'

x-env-generic-backend: &x-env-generic-backend
  TZ: Europe/Stockholm
  WHARF_API_URL: http://api:8080
  ALLOW_CORS: "YES"

services:
  proxy:
    image: amd64/traefik:v2.5
    ports:
    - "5000:8081"
    volumes:
    - ./wharf-docker-compose/traefik:/etc/traefik # Traefik configuration file
  web:
    image: quay.io/iver-wharf/wharf-web
  api:
    image: quay.io/iver-wharf/wharf-api
    ports:
    - "5001:8080"
    environment:
      <<: *x-env-generic-backend
      DBHOST: db
      DBUSER: postgres
      DBPASS: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
      DBPORT: 5432
      DBNAME: wharf
      DBLOG: "true"
      RABBITMQUSER: guest
      RABBITMQPASS: guest
      RABBITMQHOST: rabbitmq
      RABBITMQPORT: 5672
      RABBITMQVHOST:
      RABBITMQNAME: wharf_queue
      RABBITMQDISABLESSL: "true"
      RABBITMQCONNATTEMPTS: 10
      MOCK_LOCAL_CI_RESPONSE: "true"
      WHARF_INSTANCE: local
  provider-gitlab:
    image: quay.io/iver-wharf/wharf-provider-gitlab
    ports:
    - "5002:8080"
    environment:
      <<: *x-env-generic-backend
  provider-github:
    image: quay.io/iver-wharf/wharf-provider-github
    ports:
    - "5003:8080"
    environment:
      <<: *x-env-generic-backend
  provider-azuredevops:
    image: quay.io/iver-wharf/wharf-provider-azuredevops
    ports:
    - "5004:8080"
    environment:
      <<: *x-env-generic-backend
  db:
    image: postgres
    restart: always
    environment:
      <<: *x-env-generic-backend
      POSTGRES_PASSWORD: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
    ports:
      - "5432:5432"
    volumes:
      - wharf-postgresql-volume:/var/lib/postgresql/data
## Uncomment to enable RabbitMQ
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    ports:
#      - "5672:5672"
#      - "15672:15672"
volumes:
  wharf-postgresql-volume:
