[http.services]
  [[http.services.web.loadBalancer.servers]]
    url = "http://web:8080"
  [[http.services.api.loadBalancer.servers]]
    url = "http://api:8080"
  [[http.services.provider-gitlab.loadBalancer.servers]]
    url = "http://provider-gitlab:8080"
  [[http.services.provider-github.loadBalancer.servers]]
    url = "http://provider-github:8080"
  [[http.services.provider-azuredevops.loadBalancer.servers]]
    url = "http://provider-azuredevops:8080"

[http.routers]
  [http.routers.web]
    rule = "PathPrefix(`/`)"
    service = "web"
  [http.routers.api]
    rule = "PathPrefix(`/api/`)"
    service = "api"
  [http.routers.provider-gitlab]
    rule = "PathPrefix(`/import/gitlab`)"
    service = "provider-gitlab"
  [http.routers.provider-github]
    rule = "PathPrefix(`/import/github`)"
    service = "provider-github"
  [http.routers.provider-azuredevops]
    rule = "PathPrefix(`/import/azuredevops`)"
    service = "provider-azuredevops"
