[entryPoints]
  [entryPoints.http]
    address = ":8081"

[providers]
  [provider.docker]
    defaultRule = "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  [providers.file]
    watch = true
    filename = "/etc/traefik/rules.toml"

[api]
  insecure = true
  dashboard = true

[log]
  level = "WARNING"
